export const API_REQUEST="DASHBOARD/API_REQUEST"
export const API_SUCCESS="DASHBOARD/API_SUCCESS"
export const API_ERROR  ="DASHBOARD/API_ERROR"
//api
export const API_STATS_REQUEST="DASHBOARD/API_STATS_REQUEST"
export const API_STATS_SUCCESS="DASHBOARD/API_STATS_SUCCESS"
export const API_STATS_ERROR  ="DASHBOARD/API_STATS_ERROR"


export const BUSINESS_COUNT_API_REQUEST="DASHBOARD/BUSINESS_COUNT_API_REQUEST"
export const BUSINESS_COUNT_API_SUCCESS="DASHBOARD/BUSINESS_COUNT_API_SUCCESS"
export const BUSINESS_COUNT_API_FAILED="DASHBOARD/BUSINESS_COUNT_API_FAILED"


export const LIQUOR_COUNT_API_REQUEST = "DASHBOARD/LIQOUR_COUNT_API_REQUEST"
export const LIQUOR_COUNT_API_SUCCESS = "DASHBOARD/LIQOUR_COUNT_API_SUCCESS"
export const LIQUOR_COUNT_API_FAILED = "DASHBOARD/LIQOUR_COUNT_API_FAILED"


export const FOOD_COUNT_API_REQUEST="DASHBOARD/FOOD_COUNT_API_REQUEST"
export const FOOD_COUNT_API_SUCCESS="DASHBOARD/FOOD_COUNT_API_SUCCESS"
export const FOOD_COUNT_API_FAILED="DASHBOARD/FOOD_COUNT_API_FAILED"

export const BILL_COUNT_API_REQUEST="DASHBOARD/BILL_COUNT_API_REQUEST"
export const BILL_COUNT_API_SUCCESS="DASHBOARD/BILL_COUNT_API_SUCCESS"
export const BILL_COUNT_API_FAILED="DASHBOARD/BILL_COUNT_API_FAILED"
